files:
  - file:
      name: "21.x.x-SNAPSHOT.info"
      path: "\.."
      replace_values:
        - unit:
            source_row: "jedi.log.dir = D:\/RCLogs"
            new_value: RCLOGS_HOME

  - file:
      name: "standalone.conf.bat"
      path: "\bin"
      replace_values:
        - unit:
            source_row: "set \"JAVA_OPTS=%JAVA_OPTS% -Djboss.server.log.dir=D:\RCLogs\""
            new_value: RCLOGS_HOME

  - file:
      name: "logging.properties"
      path: "\standalone\configuration"
      replace_values:
        - unit:
            source_row: "handler.FILE.fileName=D\:\\RCLogs\\server.log"
            new_value: RCLOGS_HOME

  - file:
      name: "wrapper-4.2.3.conf"
      path: "\wrapper\conf"
      replace_values:
        - unit:
            source_row: "wrapper.java.additional.101=-Djboss.server.log.dir=D:\/RCLogs"
            new_value: RCLOGS_HOME
        - unit:
            source_row: "wrapper.java.additional.103=-XX:HeapDumpPath=D:\/RCLogs"
            new_value: RCLOGS_HOME

  - file:
      name: "wrapper.conf"
      path: "\wrapper\conf"
      replace_values:
        - unit:
              source_row: "wrapper.java.additional.101=-Djboss.server.log.dir=D:\/RCLogs"
            new_value: RCLOGS_HOME
        - unit:
            source_row: "wrapper.java.additional.103=-XX:HeapDumpPath=D:\/RCLogs"
            new_value: RCLOGS_HOME